// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Xrates.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118193915_IntegrationMetadataFields")]
    partial class IntegrationMetadataFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Integration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("basecurrency");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("FreqSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("freqseconds");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("ratesJsonField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ratesjsonfield");

                    b.Property<string>("timestampJsonField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timestampjsonfield");

                    b.HasKey("Name")
                        .HasName("pk_integrations");

                    b.ToTable("integrations", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "errorTest",
                            BaseCurrency = "USD",
                            Enabled = true,
                            FreqSeconds = 10,
                            Priority = 0,
                            Url = "invalidUrl",
                            ratesJsonField = "rates",
                            timestampJsonField = "date"
                        },
                        new
                        {
                            Name = "example",
                            BaseCurrency = "USD",
                            Enabled = true,
                            FreqSeconds = 10,
                            Priority = 0,
                            Url = "https://example.com",
                            ratesJsonField = "rates",
                            timestampJsonField = "timestamp"
                        },
                        new
                        {
                            Name = "frankfurter",
                            BaseCurrency = "USD",
                            Enabled = true,
                            FreqSeconds = 10,
                            Priority = 1,
                            Url = "https://api.frankfurter.dev/v1/latest?base=USD",
                            ratesJsonField = "rates",
                            timestampJsonField = "timestamp"
                        });
                });

            modelBuilder.Entity("Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_rates");

                    b.ToTable("rates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
