// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Xrates.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Integration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("FreqSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("freqseconds");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Name")
                        .HasName("pk_integrations");

                    b.ToTable("integrations", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "errorTest",
                            Enabled = true,
                            FreqSeconds = 10,
                            Priority = 0,
                            Url = "invalidUrl"
                        },
                        new
                        {
                            Name = "example",
                            Enabled = true,
                            FreqSeconds = 10,
                            Priority = 0,
                            Url = "https://example.com"
                        },
                        new
                        {
                            Name = "frankfurter",
                            Enabled = true,
                            FreqSeconds = 10,
                            Priority = 1,
                            Url = "https://api.frankfurter.dev/v1/latest?base=USD"
                        });
                });

            modelBuilder.Entity("Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_rates");

                    b.ToTable("rates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.1011m
                        },
                        new
                        {
                            Id = 2,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.1211m
                        },
                        new
                        {
                            Id = 3,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.1111m
                        },
                        new
                        {
                            Id = 4,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 2, 3, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2311m
                        },
                        new
                        {
                            Id = 5,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 2, 2, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2211m
                        },
                        new
                        {
                            Id = 6,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 2, 4, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2411m
                        },
                        new
                        {
                            Id = 7,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2111m
                        },
                        new
                        {
                            Id = 8,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.3111m
                        },
                        new
                        {
                            Id = 9,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 3, 2, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.3211m
                        },
                        new
                        {
                            Id = 10,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 3, 3, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.3311m
                        },
                        new
                        {
                            Id = 11,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 4, 3, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.4311m
                        },
                        new
                        {
                            Id = 12,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 4, 2, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.4211m
                        },
                        new
                        {
                            Id = 13,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.4111m
                        },
                        new
                        {
                            Id = 14,
                            Base = "USD",
                            Quote = "EUR",
                            Timestamp = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 0.86057873m
                        },
                        new
                        {
                            Id = 15,
                            Base = "USD",
                            Quote = "CHF",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 2.1000m
                        },
                        new
                        {
                            Id = 16,
                            Base = "USD",
                            Quote = "CHF",
                            Timestamp = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 2.2000m
                        },
                        new
                        {
                            Id = 17,
                            Base = "USD",
                            Quote = "CHF",
                            Timestamp = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 2.3000m
                        },
                        new
                        {
                            Id = 18,
                            Base = "USD",
                            Quote = "CHF",
                            Timestamp = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 2.4000m
                        },
                        new
                        {
                            Id = 19,
                            Base = "USD",
                            Quote = "CHF",
                            Timestamp = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 0.79409917m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
