// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Xrates.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115233156_Historical")]
    partial class Historical
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Integration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("integrations");

                    b.HasData(
                        new
                        {
                            Name = "frankfurter",
                            Url = "https://api.frankfurter.dev/v1/latest?base=USD"
                        });
                });

            modelBuilder.Entity("Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.1011m
                        },
                        new
                        {
                            Id = 2,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.1211m
                        },
                        new
                        {
                            Id = 3,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.1111m
                        },
                        new
                        {
                            Id = 4,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 2, 3, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2311m
                        },
                        new
                        {
                            Id = 5,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 2, 2, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2211m
                        },
                        new
                        {
                            Id = 6,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 2, 4, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2411m
                        },
                        new
                        {
                            Id = 7,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2111m
                        },
                        new
                        {
                            Id = 8,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.3111m
                        },
                        new
                        {
                            Id = 9,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 3, 2, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.3211m
                        },
                        new
                        {
                            Id = 10,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 3, 3, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.3311m
                        },
                        new
                        {
                            Id = 11,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 4, 3, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.4311m
                        },
                        new
                        {
                            Id = 12,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 4, 2, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.4211m
                        },
                        new
                        {
                            Id = 13,
                            Currency = "EUR",
                            Timestamp = new DateTime(2025, 1, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.4111m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
