// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Xrates.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Base")
                        .HasColumnType("integer");

                    b.Property<int>("Quote")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnixTs")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base = 150,
                            Quote = 46,
                            UnixTs = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.1111m
                        },
                        new
                        {
                            Id = 2,
                            Base = 150,
                            Quote = 46,
                            UnixTs = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.2111m
                        },
                        new
                        {
                            Id = 3,
                            Base = 150,
                            Quote = 46,
                            UnixTs = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.3111m
                        },
                        new
                        {
                            Id = 4,
                            Base = 150,
                            Quote = 46,
                            UnixTs = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = 1.4111m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
